### ISSUE TITLE
[FEAT] - Clear Pin should require current Pin

### ISSUE THREAD

**Issue by ThingCoDanW** [thingco/shared-frontend-libs#56]
**Which package is this related to?**

Specify the package, or if it is a new package suggest a name.

If this covers multiple packages, **if possible** open an issue for both and PR separately: this will keep the PR's scope as small as possible (plus each package needs separate version bumps & republishing after the fix has been applied).

- [x] `@thingco/auth-flows`
- [ ] `@thingco/graphviz`
- [ ] `@thingco/react-component-library`
- [ ] `@thingco/shared-types`
- [ ] `@thingco/unit-formatter`
- [ ] `@thingco/user-preferences`
- [ ] `@thingco/user-preferences-store-web`
- [ ] `@thingco/user-preferences-store-native`
- [ ] new package (`@thingco/{enter name here}`)

**Is your feature request related to a problem? Please describe.**
Any pin operations should require sucessful pin entry first - currently this is not possible with clear pin

**Describe the solution you'd like**
Add new flow to validate current pin before calling **changeDeviceSecurityType**

**Additional context**
This also adds consistency, considering change pin requires current pin to be entered first.

**Comment by ThingCoDanW** [comment]
Possibly no longer needed if we are making pin mandatory.

**Comment by DanCouper** [comment]
Yep, no longer needed: only time pin is cleared is on logout, so don't care at that point, just blow everything away
